RICONS-EOFFICE/Presentation/NHG.Web/Models/EmailSystem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NHG.Web.Models
{
    public class EmailSystem
    {
        public string port { get; set; }
        public string user { get; set; }
        public string pass { get; set; }
        public string host { get; set; }
        public bool enableSSL { get; set; }
        public string displayName { get; set; }
    }
}

RICONS-EOFFICE/Presentation/NHG.Web/Controllers/SystemController.cs
using NHG.Web.Models;
using Nop.Admin.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using NHG.Logger;
using System.Text;
using NHG.Web.Data.Services;
using System.Xml.Linq;
using NHG.Core.Functions;
using NHG.DataServices.DataClass;

namespace NHG.Web.Controllers
{
    public class SystemController : BaseController
    {
        Log4Net _logger = new Log4Net(typeof(SystemController));

        #region Action
        //
        // GET: /System/
        public ActionResult Index()
        {
            if (!IsLogged())
                return BackToLogin();
            return View();
        }

        //
        // GET: /SystemInfo/
        public ActionResult SystemInfo()
        {
            if (!IsLogged())
                return BackToLogin();
            var model = new SystemInfoModel();
            try
            {
                model.OperatingSystem = Environment.OSVersion.VersionString;
            }
            catch (Exception ex) {
                _logger.Error(ex);
            }
            try
            {
                model.AspNetInfo = RuntimeEnvironment.GetSystemVersion();
            }
            catch (Exception ex) {
                _logger.Error(ex);
            }
            try
            {
                model.IsFullTrust = AppDomain.CurrentDomain.IsFullyTrusted.ToString();
            }
            catch (Exception ex) {
                _logger.Error(ex);
            }
            model.ServerTimeZone = TimeZone.CurrentTimeZone.StandardName;
            model.ServerLocalTime = DateTime.Now.ToString("F");
            model.UtcTime = DateTime.UtcNow.ToString("F");
            model.HttpHost = this.Request.ServerVariables["HTTP_HOST"];
            ////Environment.GetEnvironmentVariable("USERNAME");
            //foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            //{
            //    model.LoadedAssemblies.Add(new SystemInfoModel.LoadedAssembly
            //    {
            //        FullName = assembly.FullName,
            //        //we cannot use Location property in medium trust
            //        //Location = assembly.Location
            //    });
            //}
            return View(model);
        }

        public ActionResult SystemLog()
        {
            if (!IsLogged())
                return BackToLogin();
            return View();
        }

        [HttpGet]
        public ActionResult EmailSystem()
        {
            if (!IsLogged())
                return BackToLogin();
            //duong dan file encryption key
            FunctionXML function = new FunctionXML(Functions.MapPath("~/Xml/Config/encryptionkey.config"));
            //lay key da ma hoa
            string strKeyEncrypt = EncDec.Decrypt(function.ReadXMLGetKeyEncrypt());

            EmailSystem model = new Models.EmailSystem();
            #region doc thong tin chung (chuc vu, nguoi ky, )
            XElement doc = XElement.Load(Functions.MapPath("~/Xml/Config/email.xml"));
            var list = doc.Elements();
            model.host = list.ElementAt(0).Value;
            model.port = list.ElementAt(1).Value;
            model.user = AES.DecryptText(list.ElementAt(2).Value, strKeyEncrypt);
            model.pass = AES.DecryptText(list.ElementAt(3).Value, strKeyEncrypt);
            model.displayName = list.ElementAt(4).Value;
            if (list.ElementAt(5).Value == "1")
                model.enableSSL = true;
            else
                model.enableSSL = false;
            #endregion
            return View(model);
        }

        [HttpPost]
        public ActionResult EmailSystem(EmailSystem model)
        {
            if (!IsLogged())
                return BackToLogin();
            //duong dan file encryption key
            FunctionXML function = new FunctionXML(Functions.MapPath("~/Xml/Config/encryptionkey.config"));
            //lay key da ma hoa
            string strKeyEncrypt = EncDec.Decrypt(function.ReadXMLGetKeyEncrypt());
            XDocument doc = new XDocument(
                new XDeclaration("1.0", "utf-8", "true"),
                new XProcessingInstruction("test", "value"),
                new XComment(String.Format("Ngày {0}   author: {1}", DateTime.Now, Session["userid"])),

                new XElement("email",
                    new XElement("smtp_host", model.host),
                    new XElement("smtp_port", model.port),
                    new XElement("smtp_user", AES.EncryptText(model.user, strKeyEncrypt)),
                    new XElement("smtp_pass", AES.EncryptText(model.pass, strKeyEncrypt)),
                    new XElement("displayName", model.displayName),
                    new XElement("enableSSL", model.enableSSL))
            );

            doc.Save(Functions.MapPath("~/Xml/Config/email.xml"));
            return View();
        }
        #endregion

        #region ajax request
        [HttpPost]
        public ActionResult ListLog(string id = "")
        {
            if (!IsLogged())
                return BackToLogin();
            LogServices service = new LogServices();
            List<LogModels> lstResult = service.SelectRows(new M_Log() { loglevel = id});
            StringBuilder result = new StringBuilder();
            StringBuilder lstRow = new StringBuilder();
            if (lstResult.Count > 0)
            {
                int i = 1;
                foreach (var item in lstResult)
                {
                    lstRow.Append(PrepareDataJsonForListLog(item));
                    i++;
                }
                if (lstRow.Length > 0)
                    lstRow.Remove(lstRow.Length - 1, 1);
            }
            result.Append("{");
            result.Append("\"isHeader\":\"" + "111" + "\",");
            result.Append("\"Pages\":\"" + "212" + "\",");
            result.Append("\"data\":[" + lstRow.ToString() + "]");
            result.Append("}");
            return Json(result.ToString(), JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Method
        private StringBuilder PrepareDataJsonForListLog(LogModels model)
        {
            StringBuilder sbResult = new StringBuilder();
            try
            {
                sbResult.Append("{");
                sbResult.Append("\"col_class\":\"rows-box\",");
                sbResult.Append("\"col_id\":\"" + "323" + "\",");
                sbResult.Append("\"col_value\":[");
                #region Data cell
                //stt
                sbResult.Append("{");
                sbResult.Append("\"colspan\":\"1\",");
                sbResult.Append("\"col_class\":\"ovh col1 stt\",");
                sbResult.Append("\"col_id\":\"6\",");
                sbResult.Append("\"col_value\":\"" + model.stt + "\"");
                sbResult.Append("},");
                //noi dung
                sbResult.Append("{");
                sbResult.Append("\"colspan\":\"1\",");
                sbResult.Append("\"col_class\":\"ovh col2\",");
                sbResult.Append("\"col_id\":\"6\",");
                sbResult.Append("\"title\":\"" + "23" + "\",");
                sbResult.Append("\"col_value\":\"" + model.NoiDung + "\"");
                sbResult.Append("},");
                //cap do
                sbResult.Append("{");
                sbResult.Append("\"colspan\":\"1\",");
                sbResult.Append("\"col_class\":\"ovh col3\",");
                sbResult.Append("\"col_id\":\"6\",");
                sbResult.Append("\"title\":\"" + "323" + "\",");
                sbResult.Append("\"col_value\":\"" + model.CapDo + "\"");
                sbResult.Append("},");
                //ngay nhap
                sbResult.Append("{");
                sbResult.Append("\"colspan\":\"1\",");
                sbResult.Append("\"col_class\":\"ovh col4\",");
                sbResult.Append("\"col_id\":\"6\",");
                sbResult.Append("\"col_value\":\"" + model.NgayTao + "\"");
                sbResult.Append("}");
                
                #endregion

                sbResult.Append("]");
                sbResult.Append("},");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
            }
            return sbResult;
        }
        #endregion
    }
}

RICONS-EOFFICE/Presentation/NHG.Web/Views/System/EmailSystem.cshtml
@{
    ViewBag.Title = "Email hệ thống";
}
@model NHG.Web.Models.EmailSystem
@*--css--*@
@section CSS
{
    <link rel="stylesheet" type="text/css" href="@Url.Content("~")themes/NHG-2015/css/controller/System.EmailSystemCSS.css" />
}

@*--javascript--*@
@section JavaScript
{
    <script type="text/javascript" src="@Url.Content("~")themes/NHG-2015/js/controllers/System.EmailSystemJS.js"></script>
}
<div class="HeaderFixed">
    <div class="b-b b-light">
        <div class="p-left c-black">Email hệ thống</div>
        <div class="clearBoth"></div>
    </div>
</div>
@if (Model != null)
{
    <div class="boxEdit">
        @using (Html.BeginForm("EmailSystem", "System", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
        {
            <table>
                <tr>
                    <td>Tên hiển thị</td>
                    <td><input type="text" name="displayName" value="@Model.displayName" autocomplete="off"/></td>
                </tr>
                <tr>
                    <td>Host</td>
                    <td><input type="text" name="host" value="@Model.host" autocomplete="off" /></td>
                </tr>
                <tr>
                    <td>Port</td>
                    <td><input type="text" name="port" value="@Model.port" autocomplete="off" /></td>
                </tr>
                <tr>
                    <td>Tên đăng nhập</td>
                    <td><input type="text" name="user" value="@Model.user" autocomplete="off" /></td>
                </tr>
                <tr>
                    <td>Mật khẩu</td>
                    <td><input type="password" name="pass" value="@Model.pass" autocomplete="off" /></td>
                </tr>
                <tr>
                    <td>Kích hoạt SSL</td>
                    <td><input type="checkbox" name="enableSSL" value="@Model.enableSSL" autocomplete="off" /></td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" class="buttoncustom WhiteButton" value="Lưu" /></td>
                </tr>
            </table>
        }
    </div>
}

RICONS-EOFFICE/Presentation/NHG.Web/Views/System/SystemInfo.cshtml
@model NHG.Web.Models.SystemInfoModel
@{
    ViewBag.Title = "Thông tin hệ thống";
}

@*--css--*@
@section CSS
{
    <link rel="stylesheet" type="text/css" href="@Url.Content("~")themes/NHG-2015/css/controller/System.SystemInfoCSS.css" />
}

<div class="HeaderFixed">
    <div class="b-b b-light">
        <div class="p-left c-black">Thông tin hệ thống</div>
        <div class="clearBoth"></div>
    </div>
</div>
<table class="adminContent">
    <tr>
        <td class="adminTitle">
            Hệ điều hành
        </td>
        <td class="se">:</td>
        <td class="adminData">
            @Model.OperatingSystem
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            Phiên bản Asp.Net
        </td>
        <td class="se">:</td>
        <td class="adminData">
            @Model.AspNetInfo
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            Múi giờ
        </td>
        <td class="se">:</td>
        <td class="adminData">
            @Model.ServerTimeZone
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            Thời gian trên Server
        </td>
        <td class="se">:</td>
        <td class="adminData">
            @Model.ServerLocalTime
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
           GMT/UTC
        </td>
        <td class="se">:</td>
        <td class="adminData">
            @Model.UtcTime
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            HTTP_HOST
        </td>
        <td class="se">:</td>
        <td class="adminData">
            @Model.HttpHost
        </td>
    </tr>
</table>

RICONS-EOFFICE/Presentation/NHG.Web/Views/System/SystemLog.cshtml
@{
    ViewBag.Title = "SystemLog";
}

@*--css--*@
@section CSS
{
    <link rel="stylesheet" type="text/css" href="@Url.Content("~")themes/NHG-2015/css/controller/System.SystemLogCSS.css" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~")themes/NHG-2015/css/chosen/chosen.css" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~")themes/NHG-2015/css/chosen/prism.css" />
}

@*--javascript--*@
@section JavaScript
{
    <script type="text/javascript" src="@Url.Content("~")themes/NHG-2015/js/controllers/System.SystemLogJS.js"></script>
    <script type="text/javascript" src="@Url.Content("~")themes/NHG-2015/js/chosen/chosen.jquery.js"></script>
    <script type="text/javascript" src="@Url.Content("~")themes/NHG-2015/js/chosen/prism.js"></script>
    <script type="text/javascript" src="@Url.Content("~")themes/NHG-2015/js/table/buildTable.js"></script>
    <script type="text/javascript" src="@Url.Content("~")themes/NHG-2015/js/colResizale/colResizable-1.3.source.js"></script>
}
<script>
    var linkContent = '@Url.Content("~")';
</script>
<div class="HeaderFixed">
    <div class="b-b b-light">
        <div class="p-left c-black">Lịch sử hoạt động</div>
        <div class="p-right">
            <div class="p-right-item t-fillter c-black">Lọc theo:&nbsp;</div>
            <div class="p-right-item">
                <select id="filter01" data-placeholder="Chọn kế hoạch..." class="chosen-select-plan">
                    <option value="0">Tất cả</option>
                    <option value="1">ERROR</option>
                    <option value="2">INFO</option>
                    <option value="3">WARNING</option>
                </select>
            </div>
            <div class="p-right-item t-export c-black">Export: </div>
            <div class="p-right-item t-action"><i class="fa fa-file-excel-o"></i>Excel</div>
            <div class="p-right-item t-action"><i class="fa fa-print"></i>Print</div>
        </div>
        <div class="clearBoth"></div>
    </div>
</div>
<div id="boxContent">
    <div class="boxTable boxTable1">
        <table class="table_danhSach table_fixed" id="tableFixedHeader">
        </table>
    </div>
    <div class="boxTable boxTable2">
        <table class="table_danhSach table_fixed" id="tableContent">
            <thead>

            </thead>
            <tbody>

            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4" id="girdInfo">Tổng số: <span class="currentRow">1</span>/<span class="sumRow">212</span></td>
                </tr>
                <tr>
                    <td colspan="4" id="girdInfoLoad">
                        <div class="divExentd"><i class="retweet_32"></i>Xem thêm</div>
                    </td>
                </tr>
                <tr>
                    <td colspan="4" id="footerInfo">
                        <div class="companyName">CÔNG TY CỔ PHẦN ĐẦU TU PHÁT TRIỂN NGUYỄN HOÀNG</div>
                        <div class="address">49 Phạm Ngọc Thạch, P.6, Q3, TP.HCM</div>
</td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>